### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by asquithea** [usethesource/capsule#1]
Highly recommend releasing to Maven Central if you think it's ready.

**Comment by msteindorfer** [comment]
In future we plan to release builds to Maven Central. At the moment Capsule as a standalone library is very young; it was recently extracted from [usethesource/rascal-value](https://github.com/usethesource/rascal-value) and still has to undergo API refactoring before being suitable for Maven Central. I added a milestone for this issue.

**Comment by jitpack-io** [comment]
Hi all
In that case you might find this useful: https://jitpack.io/#usethesource/capsule
Capsule is available as a maven dependency on JitPack.

**Comment by msteindorfer** [comment]
For the time being, binary capsule artifacts won't be published on maven central. However, they are available from a separate maven repository. I updated the README on how to consume capsule as a dependency.

**Comment by vlsi** [comment]
@msteindorfer , would you please re-evaluate publishing to central?

I see no issues with publishing to Central even in the case the API is not stable.
As you settle on the method names, you could bump the version.

I see Gradle team evaluates `capsule` https://github.com/gradle/gradle/pull/17702

In my experiments (append-only maps), `capsue` consumes slightly more space than `com.github.andrewoma.dexx.collection.HashMap`, however, `capsule` is faster, so I'm inclined to switch https://github.com/vlsi/compactmap to `capsule` as well, however, it would be complicate the consumption as everyone who adds a dependency would need to add `capsule maven` repository (which is non-trivial in enterprise environments)
