### ISSUE TITLE
Incorrect Maven repo URL

### ISSUE THREAD

**Issue by pniederw** [usethesource/capsule#11]
`http://nexus.rascal-mpl.org/repository/maven-public/`, as given in the README, doesn't work.

**Comment by pniederw** [comment]
Probably should be `http://nexus.usethesource.io/content/repositories/public/`.

**Comment by msteindorfer** [comment]
Thanks for pointing out. We recently switched from Nexus 3 back to Nexus 2 and also changed the URL of the CI server. I'll fix it immediately.
