### ISSUE TITLE
`values` fails on `AbstractSpecialisedImmutableMap` if there are duplicate values

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/capsule#12]
For small maps, there are some special instances which use fields instead of a Trie.

For a map of 2 entries, if you call `.values()` on it, and the values are the same, you get an exception that no duplicate keys are allowed.

Looking at the code in `io.usethesource.capsule.AbstractSpecialisedImmutableMap<K, V>` we see there is a TODO warning for this case:

```
    @Override
    public Collection<V> values() {
        // TODO: will fail if two values are equals; return listOf(...)
        return AbstractSpecialisedImmutableSet.setOf(val1, val2);
    }
```

**Comment by msteindorfer** [comment]
This issue is resolved in release `0.2.2`.
