### ISSUE TITLE
This package contains no tests

### ISSUE THREAD

**Issue by thedrow** [usethesource/capsule#15]
If this library is to be used as a reference implementation to CHAMP it should contain tests that will allow porters to verify the implementation.
The tests will also uncover bugs in this implementation.
Please cover this package with tests we can all use.

**Comment by msteindorfer** [comment]
The sub module [capsule-veritas](https://github.com/usethesource/capsule/tree/master/capsule-veritas) contains a test suite of property-based tests that extensively exercise Capsule's data structures with randomly generated inputs. The test suite runs on our continuous integration server after each commit. In summary, this package has tests attached and tests are continuously added over time.

It is not in the scope of Capsule to provide a generic testing infrastructure for ports. However, feel free to reuse the test suite for testing your own implementation, in case you're willing to work yourself through the source code of the testing infrastructure.

**Comment by thedrow** [comment]
I wasn't talking about generic testing infrastructure :) I was talking about some form of testing that porters can port themselves. These work. They are just not easy to find.
