### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by Robson96** [usethesource/capsule#25]
Do you intend to implement other types of collections for example: Lists, Linked Lists, Queues, etc ...?

**Comment by jurgenvinju** [comment]
Hi. We were thinking of adding vectors at a time but for now no such plans. The capsule library is used in usethesource/vallang where we have immutable lists, and tree nodes and such. Why do you ask? I'm interested to know why you're interested.

**Comment by Robson96** [comment]
I asked why I found your project very interesting, and your thesis, I want to create a project on the web and immutable and persistent structures have many advantages! :)

**Comment by jurgenvinju** [comment]
True. Just to be clear, It wasn't my thesis but by  @msteindorfer . I'm just the supervisor. We use this project everyday for relational calculus allocations so it's important to us. N

**Comment by FrankC01** [comment]
It's a wonderful repo.... I'm thinking of doing a Rust port....
